
services:
  mysql:
    image: mysql:lts
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_todoapp
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis/redis-stack:7.2.0-v14
    container_name: redis
    ports:
      - 6379:6379
      - 8001:8001
    environment:
      REDIS_ARGS: "--requirepass admin --save 20 1 --loglevel warning"
    command: [ "/entrypoint.sh", "./conf/redis-stack.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data
  
  mongo:
    image: mongo:8.0.6
    container_name: mongo
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo_data:/data/db
      - ./data/mongo:/backupdb


volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  mongo_data:
    driver: local