# Creation date : 16.10.2023
# Created by : MMN
# Description : Create two containers: mongo db and mongo express
# 

services:
  mongo2:
    image: mongo
    container_name: mongo2
    hostname: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodata:/data/db
      - ./backupdb:/backupdb
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodata:
